# usage: ansible-playbook make-25-vms.yml

---
- hosts: localhost
  gather_facts: no

  tasks:
    - name: Login to RHV
      ovirt_auth:
        url: https://engine.supermicro.com/ovirt-engine/api
        insecure: yes
        username: admin@internal
        password: redhat

    - name: Create VMs
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        cluster: Default
        template: RHEL7.6_Setup
        name: "{{ item }}"
        state: running
        instance_type: Tiny
        nics:
          - name: nic1
            profile_name: ovirtmgmt
        cloud_init:
          host_name: "{{ item }}.supermicro.com"
          user_name: root
          root_password: redhat
          nic_name: eth0
          nic_on_boot: true
          nic_boot_protocol: dhcp

          custom_script: |
            runcmd:
              - hostnamectl set-hostname {{ item }}.supermicro.com
              - yum -y remove cloud-init
        wait: true
      with_items:
         - vm01
         - vm02
         - vm03
    - name: Cleanup RHV auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
